apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eccomerce-lab-rabbitmq
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  project: default
  source:
    chart: rabbitmq
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 14.4.4
    helm:
      parameters:
        - name: auth.username
          value: rabbitmq
        - name: auth.password
          value: rabbitmq-password
        - name: persistence.size
          value: 1Gi
  syncPolicy:
    automated: {}
