apiVersion: v1
kind: Service
metadata:
  name: buy-api-service
spec:
  ports:
  - name: http
    port: 3001
    targetPort: 3001
  selector:
    app: buy-api
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: buy-api
  labels:
    app: buy-api
spec:
  # do not include replicas in the manifests if you want replicas to be controlled by HPA
  replicas: 1
  selector:
    matchLabels:
      app: buy-api
  template:
    metadata:
      labels:
        app: buy-api
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: buy-api
        image: gustavoapolinario/ecommerce-lab-buy-api
        ports:
        - containerPort: 3001
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: "PORT"
          value: "3001"
        - name: "PRODUCT_API_URL"
          value: "http://product-api-service:3000" # use service to connect on pod internally
        - name: "RABBITMQ_ENDPOINT"
          value: "rabbitmq"
        - name: "RABBITMQ_PORT"
          value: "5672"
        - name: "RABBITMQ_USERNAME"
          value: "rabbitmq"
        - name: "RABBITMQ_PASSWORD"
          value: "rabbitmq-password"
        - name: "REDIS_ENDPOINT"
          value: "redis-master"
        - name: "REDIS_PORT"
          value: "6379"
        - name: "REDIS_USERNAME"
          value: "default"
        - name: "REDIS_PASSWORD"
          value: "your_redis_password"
