apiVersion: v1
kind: Service
metadata:
  name: product-api-service
spec:
  ports:
  - name: http
    port: 3000
    targetPort: 3000
  selector:
    app: product-api
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-api
  labels:
    app: product-api
spec:
  # do not include replicas in the manifests if you want replicas to be controlled by HPA
  replicas: 1
  selector:
    matchLabels:
      app: product-api
  template:
    metadata:
      labels:
        app: product-api
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: product-api
        image: gustavoapolinario/ecommerce-lab-product-api
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: PORT
          value: "3000"
        - name: MONGODB_ENDPOINT
          value: "mongo-mongodb"
        - name: MONGODB_PORT
          value: "27017"
        - name: MONGODB_USERNAME
          value: "product-api"
        - name: MONGODB_PASSWORD
          value: "product-api-password"
        - name: MONGODB_DATABASE
          value: "products"
        - name: REDIS_ENDPOINT
          value: "redis-master"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_USERNAME
          value: "default"
        - name: REDIS_PASSWORD
          value: "your_redis_password"
