apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eccomerce-lab-kafka
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  project: default
  source:
    chart: kafka
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 29.3.4
    helm:
      parameters:
        - name: auth.enabled
          value: "false"
        - name: controller.persistence.size
          value: 1Gi
        - name: zookeeper.persistence.size
          value: 1Gi
        - name: controller.replicaCount
          value: "1"
        - name: zookeeper.replicaCount
          value: "1"
        - name: listeners.client.protocol
          value: PLAINTEXT
  syncPolicy:
    automated: {}
