apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eccomerce-lab-mongodb
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  project: default
  source:
    chart: mongodb
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 15.6.9
    helm:
      parameters:
        - name: auth.username
          value: product-api
        - name: auth.password
          value: product-api-password
        - name: auth.database
          value: products
        - name: persistence.size
          value: 1Gi
        - name: initdbScriptsConfigMap
          value: mongo-init-configmap
  syncPolicy:
    automated: {}

